In [1]:
import matplotlib.pyplot
import plotly
import pandas as pd
import cufflinks as cf
import numpy as np
import torch


$$y=2x_1-3.4x_2+4.2$$

In [2]:
def train_data(num,para_num,w):
    x=torch.ones(num,para_num)#加一个维，用于偏置
    norm_x=torch.normal(0,1,(num,para_num-1))
    x[:,:para_num-1]=norm_x[:,:para_num-1]
    y=torch.mv(x,w)+torch.normal(0,0.1,(num,1))[:,0]
    return(np.array(x[:,:2]),np.array(y))


para_num=3
data_num=10
t=train_data(data_num,para_num,torch.tensor([2.,-3.4,4.2]))
t

(array([[-0.0645403 , -0.38771424],
        [-1.2991486 ,  0.9628772 ],
        [-0.13090052,  0.3777924 ],
        [-0.6400795 ,  1.6803416 ],
        [ 1.0216033 ,  0.7803475 ],
        [ 1.4835794 , -0.35222077],
        [-1.2295136 , -0.4356728 ],
        [-1.0413718 , -0.75628924],
        [-0.75428796,  0.5212332 ],
        [ 2.4252093 , -0.01884051]], dtype=float32),
 array([ 5.3310513, -1.6202087,  2.6235218, -2.9220994,  3.3421085,
         8.268075 ,  3.2728345,  4.796761 ,  0.932385 ,  8.977914 ],
       dtype=float32))

$$X=\begin{bmatrix}1&X_{11}&\cdots&X_{1(m-1)}&X_{1m}\\
1&X_{21}&\cdots&X_{2(m-1)}&X_{2m}\\
1&X_{31}&\cdots&X_{3(m-1)}&X_{3m}\\
\vdots& \vdots&\vdots&\vdots&\vdots\\
1&X_{n1}&\cdots&X_{n(m-1)}&X_{nm}\\
\end{bmatrix}$$

In [3]:
X=np.ones((data_num,para_num))
Y=t[1]
X[:,1:]=t[0]
X

array([[ 1.        , -0.0645403 , -0.38771424],
       [ 1.        , -1.29914856,  0.96287721],
       [ 1.        , -0.13090052,  0.37779239],
       [ 1.        , -0.6400795 ,  1.6803416 ],
       [ 1.        ,  1.02160335,  0.78034753],
       [ 1.        ,  1.4835794 , -0.35222077],
       [ 1.        , -1.22951365, -0.43567279],
       [ 1.        , -1.04137182, -0.75628924],
       [ 1.        , -0.75428796,  0.5212332 ],
       [ 1.        ,  2.42520928, -0.01884051]])

$$\beta=(X^TX)^{-1}X^TY$$

In [4]:
beta=np.linalg.inv(np.matmul(X.T,X))
beta=np.dot(beta,X.T)
beta=np.dot(beta,Y)
beta

array([ 4.16789928,  1.93184589, -3.47128698])

In [5]:
import plotly.graph_objects as go
fig=go.Figure()
fig.add_trace(go.Scatter3d(x=X[:,1],y=X[:,2],z=Y,mode="markers"))
a=np.linspace(X[:,1].min()-0.2,X[:,1].max()+0.2,50)
b=np.linspace(X[:,2].min()-0.2,X[:,2].max()+0.2,50)
x,y=np.meshgrid(a,b)
z=beta[0]+beta[1]*x+beta[2]*y

fig.add_trace(go.Surface(x=x,y=y,z=z,opacity=0.8))

In [6]:
z

array([[ 4.5913297 ,  4.75393427,  4.91653883, ..., 12.23374431,
        12.39634888, 12.55895344],
       [ 4.39037542,  4.55297999,  4.71558455, ..., 12.03279003,
        12.1953946 , 12.35799916],
       [ 4.18942114,  4.35202571,  4.51463027, ..., 11.83183575,
        11.99444032, 12.15704488],
       ...,
       [-4.85352147, -4.6909169 , -4.52831234, ...,  2.78889314,
         2.95149771,  3.11410228],
       [-5.05447575, -4.89187118, -4.72926662, ...,  2.58793886,
         2.75054343,  2.913148  ],
       [-5.25543003, -5.09282546, -4.9302209 , ...,  2.38698458,
         2.54958915,  2.71219372]])