In [42]:
import matplotlib.pyplot
import plotly
import pandas as pd
import cufflinks as cf
import numpy as np
import torch


$$y=2x_1-3.4x_2+4.2$$

In [43]:
def train_data(num,para_num,w):
    x=torch.ones(num,para_num)#加一个维，用于偏置
    norm_x=torch.normal(0,1,(num,para_num-1))
    x[:,:para_num-1]=norm_x[:,:para_num-1]
    y=torch.mv(x,w)+torch.normal(0,0.1,(num,1))[:,0]
    return(np.array(x[:,:2]),np.array(y))


para_num=3
data_num=10
t=train_data(data_num,para_num,torch.tensor([2.,-3.4,4.2]))
t

(array([[ 0.32621148, -0.7659614 ],
        [ 1.0990927 ,  0.88182193],
        [-0.85035145, -0.35860464],
        [-0.85498595, -0.42438462],
        [ 1.5079296 , -1.427127  ],
        [-0.8083264 , -0.1899453 ],
        [ 0.70609474, -0.73977554],
        [-1.4615246 ,  0.2256114 ],
        [-1.5637095 , -0.31319165],
        [ 0.01001283,  1.073839  ]], dtype=float32),
 array([ 7.4527345 ,  3.34205   ,  3.6733308 ,  3.76101   , 12.199992  ,
         3.0342271 ,  8.08699   ,  0.78390396,  2.0314507 ,  0.46997875],
       dtype=float32))

$$X=\begin{bmatrix}1&X_{11}&\cdots&X_{1(m-1)}&X_{1m}\\
1&X_{21}&\cdots&X_{2(m-1)}&X_{2m}\\
1&X_{31}&\cdots&X_{3(m-1)}&X_{3m}\\
\vdots& \vdots&\vdots&\vdots&\vdots\\
1&X_{n1}&\cdots&X_{n(m-1)}&X_{nm}\\
\end{bmatrix}$$

In [44]:
X=np.ones((data_num,para_num))
Y=t[1]
X[:,1:]=t[0]
X

array([[ 1.        ,  0.32621148, -0.76596141],
       [ 1.        ,  1.09909272,  0.88182193],
       [ 1.        , -0.85035145, -0.35860464],
       [ 1.        , -0.85498595, -0.42438462],
       [ 1.        ,  1.50792956, -1.427127  ],
       [ 1.        , -0.80832642, -0.1899453 ],
       [ 1.        ,  0.70609474, -0.73977554],
       [ 1.        , -1.46152461,  0.2256114 ],
       [ 1.        , -1.5637095 , -0.31319165],
       [ 1.        ,  0.01001283,  1.07383895]])

$$\beta=(X^TX)^{-1}X^TY$$

In [45]:
beta=np.linalg.inv(np.matmul(X.T,X))
beta=np.dot(beta,X.T)
beta=np.dot(beta,Y)
beta

array([ 4.16525826,  2.01122051, -3.42706948])

In [54]:
import plotly.graph_objects as go
fig=go.Figure()
fig.add_trace(go.Scatter3d(x=X[:,1],y=X[:,2],z=Y,mode="markers"))
a=np.linspace(X[:,1].min()-0.2,X[:,1].max()+0.2,50)
b=np.linspace(X[:,2].min()-0.2,X[:,2].max()+0.2,50)
x,y=np.meshgrid(a,b)
z=beta[0]+beta[1]*x+beta[2]*y

fig.add_trace(go.Surface(x=x,y=y,z=z,opacity=0.8))