$$\left(\begin{array}{l}p_1^{(n+1)}\\p_2^{(n+1)}\end{array}\right )=\left(\begin{array}{l}p_{11}& p_{21}\\p_{12}& p_{22}\end{array}\right )\left(\begin{array}{l}p_1^{(n)}\\p_2^{(n)}\end{array}\right )$$

In [186]:
import numpy as np
import pandas as pd

P0=np.array([1,0])#初始概率分布
P1=np.array([0,1])
T1=np.array([[0.95,0.05],[0.9,0.1]])
T2=np.array([[0.95,0.05],[0.6,0.4]])
Q1=np.array([10,-9])#收益
Q2=np.array([10,-6])

In [187]:
def dotx(a,n):
    if n==0:
        return 1
    else:
        for i in range(1,n+1):
            if i == 1:
                b = a
            else :
                b = np.dot(a,b)
        return b    

def dotn(*para):
    ans=para[0]
    for i in range(1,len(para)):
        ans=np.dot(para[i],ans)
    return ans

def generate(Q0,T,n,P0):
    T1=dotx(T,n)
    return dotn(T1,P0,Q0)

ans1=[generate(Q1,T1,i,P0) for i in range(11)]
pd.Series(ans1)


0     10.000000
1      9.050000
2      9.002500
3      9.000125
4      9.000006
5      9.000000
6      9.000000
7      9.000000
8      9.000000
9      9.000000
10     9.000000
dtype: float64

In [188]:
ans2=[generate(Q2,T2,i,P0) for i in range(11)]
pd.Series(ans2)

0     10.000000
1      9.200000
2      8.920000
3      8.822000
4      8.787700
5      8.775695
6      8.771493
7      8.770023
8      8.769508
9      8.769328
10     8.769265
dtype: float64

In [189]:
pd.Series([generate(Q1,T1,i,P0) for i in range(11)]).cumsum()

0      10.000000
1      19.050000
2      28.052500
3      37.052625
4      46.052631
5      55.052632
6      64.052632
7      73.052632
8      82.052632
9      91.052632
10    100.052632
dtype: float64

$$w=w\text{P},w为平稳分布$$
$$设w=(w_1,w_2,\cdots),\sum_{i=1}^nw_i=1$$

In [190]:
T2=np.array([[0.95,0.05],[0.6,0.4]]).T#注意行列，使用列向量的话是左乘矩阵，需要转置

In [191]:
#求特征值和向量,以列向量排列
np.dot(T2,np.linalg.eig(T2)[1][:,0]),np.linalg.eig(T2)[1][:,0]

(array([0.99654576, 0.08304548]), array([0.99654576, 0.08304548]))

In [192]:
num=30
ans=np.array([P1.T])
for i in range(num):
    P1=np.matmul(T2,P1.T)
    ans=np.append(ans,[P1.T],axis=0)
import plotly.graph_objects as go
fig=go.Figure()
fig.add_trace(go.Scatter(x=ans[:,0],y=ans[:,1]))

In [193]:
ans

array([[0.        , 1.        ],
       [0.6       , 0.4       ],
       [0.81      , 0.19      ],
       [0.8835    , 0.1165    ],
       [0.909225  , 0.090775  ],
       [0.91822875, 0.08177125],
       [0.92138006, 0.07861994],
       [0.92248302, 0.07751698],
       [0.92286906, 0.07713094],
       [0.92300417, 0.07699583],
       [0.92305146, 0.07694854],
       [0.92306801, 0.07693199],
       [0.9230738 , 0.0769262 ],
       [0.92307583, 0.07692417],
       [0.92307654, 0.07692346],
       [0.92307679, 0.07692321],
       [0.92307688, 0.07692312],
       [0.92307691, 0.07692309],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.92307692, 0.07692308],
       [0.

$$m\alpha+n\beta =[0,1]\\
\begin{bmatrix}
  m&n
\end{bmatrix}\begin{bmatrix}
 \alpha_1 & \beta_1\\
\alpha_2  &\beta_2

\end{bmatrix}^T=[0,1]
$$ 

In [194]:
#解出系数
x=np.linalg.solve(np.linalg.eig(T2)[1],[0,1])
x,np.linalg.eig(T2)

(array([0.92627651, 1.3054279 ]),
 (array([1.  , 0.35]),
  array([[ 0.99654576, -0.70710678],
         [ 0.08304548,  0.70710678]])))

$$P_n=m\lambda_1^n\alpha+n\lambda_2^n\beta$$

In [195]:
times=100
m=x[0]
n=x[1]
alpha=np.linalg.eig(T2)[1][:,0]
beta=np.linalg.eig(T2)[1][:,1]
Pn=m*(np.linalg.eig(T2)[0][0]**times)*alpha+n*(np.linalg.eig(T2)[0][1]**times)*beta
Pn

array([0.92307692, 0.07692308])

In [196]:
m*alpha
#这就是结果，一定会存在一个特征值为1的特征向量

array([0.92307692, 0.07692308])