In [34]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import cufflinks as cf

data=pd.read_csv("data/university_data.csv")
data

Rank                                   Name  Overall  Teaching  Research  \
0      1                   University of Oxford     95.4      90.5      99.6   
1      2     California Institute of Technology     94.5      92.1      97.2   
2      3                University of Cambridge     94.4      91.4      98.7   
3      4                    Stanford University     94.3      92.8      96.4   
4      5  Massachusetts Institute of Technology     93.6      90.5      92.4   
5      6                   Princeton University     93.2      90.3      96.3   
6      7                     Harvard University     93.0      89.2      98.6   
7      8                        Yale University     91.7      92.0      94.8   
8      9                  University of Chicago     90.2      89.1      91.4   
9     10                Imperial College London     89.8      84.5      87.6   
10    11             University of Pennsylvania     89.6      87.5      90.4   
11    12               Johns Hopkins University     89.2      81.7      91.4   
12    13      University of California，Berkeley     88.3      83.0      90.6   
13    13                             ETH Zurich     88.3      81.8      92.8   
14    15                                    UCL     87.1      77.8      88.7   
15    16                    Columbia University     87.0      85.6      82.6   
16    17            University of California，LA     86.8      83.1      88.6   
17    18                  University of Toronto     85.5      76.6      89.5   
18    19                     Cornell University     85.1      79.7      86.0   
19    20                        Duke University     84.0      82.4      76.8   

    Citations  Industry Income  International Outlook  
0        98.4             65.5                   96.4  
1        97.9             88.0                   82.5  
2        95.8             59.3                   95.0  
3        99.9             66.2                   79.5  
4        99.5             86.9                   89.0  
5        98.8             58.6                   81.1  
6        99.1             47.3                   76.3  
7        97.3             52.4                   68.7  
8        96.7             52.7                   76.0  
9        97.0             69.9                   97.1  
10       98.2             74.0                   65.0  
11       98.3             91.3                   73.2  
12       99.2             46.1                   70.4  
13       90.3             56.8                   98.2  
14       96.1             42.7                   96.2  
15       98.2             44.8                   79.3  
16       97.3             51.3                   64.1  
17       93.6             50.5                   84.7  
18       96.6             37.1                   73.4  
19       97.0             99.9                   61.5

In [35]:
J=len(data.columns[3:])
I=len(data)
X=np.zeros((I,J))
for j in range(J):
    X[:,j]=data[data.columns[3:][j]]
X

array([[90.5, 99.6, 98.4, 65.5, 96.4],
       [92.1, 97.2, 97.9, 88. , 82.5],
       [91.4, 98.7, 95.8, 59.3, 95. ],
       [92.8, 96.4, 99.9, 66.2, 79.5],
       [90.5, 92.4, 99.5, 86.9, 89. ],
       [90.3, 96.3, 98.8, 58.6, 81.1],
       [89.2, 98.6, 99.1, 47.3, 76.3],
       [92. , 94.8, 97.3, 52.4, 68.7],
       [89.1, 91.4, 96.7, 52.7, 76. ],
       [84.5, 87.6, 97. , 69.9, 97.1],
       [87.5, 90.4, 98.2, 74. , 65. ],
       [81.7, 91.4, 98.3, 91.3, 73.2],
       [83. , 90.6, 99.2, 46.1, 70.4],
       [81.8, 92.8, 90.3, 56.8, 98.2],
       [77.8, 88.7, 96.1, 42.7, 96.2],
       [85.6, 82.6, 98.2, 44.8, 79.3],
       [83.1, 88.6, 97.3, 51.3, 64.1],
       [76.6, 89.5, 93.6, 50.5, 84.7],
       [79.7, 86. , 96.6, 37.1, 73.4],
       [82.4, 76.8, 97. , 99.9, 61.5]])

In [36]:
#去量纲
for j in range(J):
    X[:,j]/=np.linalg.norm(X[:,j])
X

array([[0.2346978 , 0.24289646, 0.22617258, 0.22722118, 0.2654663 ],
       [0.23884715, 0.23704353, 0.22502333, 0.30527426, 0.22718848],
       [0.23703181, 0.24070161, 0.22019648, 0.20571322, 0.26161098],
       [0.24066249, 0.23509256, 0.22962034, 0.2296495 , 0.21892708],
       [0.2346978 , 0.22533768, 0.22870094, 0.30145833, 0.24508818],
       [0.23417913, 0.23484868, 0.22709198, 0.2032849 , 0.22333316],
       [0.23132645, 0.24045774, 0.22778153, 0.16408491, 0.21011493],
       [0.23858782, 0.2311906 , 0.22364423, 0.18177694, 0.18918605],
       [0.23106711, 0.22289896, 0.22226513, 0.18281765, 0.20928879],
       [0.21913772, 0.21363182, 0.22295468, 0.24248489, 0.26739396],
       [0.22691776, 0.22046024, 0.22571288, 0.2567079 , 0.17899699],
       [0.21187635, 0.22289896, 0.22594273, 0.31672204, 0.20157815],
       [0.2152477 , 0.22094798, 0.22801138, 0.15992208, 0.19386751],
       [0.21213569, 0.22631317, 0.20755472, 0.19704066, 0.27042314],
       [0.2017623 , 0.21631442, 0.

In [37]:
W=np.array([0.3,0.3,0.3,0.025,0.075])
V=np.zeros((I,J))
for i in range(I):
    V[i,:]=X[i,:]*W
V

array([[0.07040934, 0.07286894, 0.06785177, 0.00568053, 0.01990997],
       [0.07165415, 0.07111306, 0.067507  , 0.00763186, 0.01703914],
       [0.07110954, 0.07221048, 0.06605894, 0.00514283, 0.01962082],
       [0.07219875, 0.07052777, 0.0688861 , 0.00574124, 0.01641953],
       [0.07040934, 0.0676013 , 0.06861028, 0.00753646, 0.01838161],
       [0.07025374, 0.07045461, 0.0681276 , 0.00508212, 0.01674999],
       [0.06939793, 0.07213732, 0.06833446, 0.00410212, 0.01575862],
       [0.07157634, 0.06935718, 0.06709327, 0.00454442, 0.01418895],
       [0.06932013, 0.06686969, 0.06667954, 0.00457044, 0.01569666],
       [0.06574132, 0.06408955, 0.0668864 , 0.00606212, 0.02005455],
       [0.06807533, 0.06613807, 0.06771386, 0.0064177 , 0.01342477],
       [0.06356291, 0.06686969, 0.06778282, 0.00791805, 0.01511836],
       [0.06457431, 0.06628439, 0.06840342, 0.00399805, 0.01454006],
       [0.06364071, 0.06789395, 0.06226642, 0.00492602, 0.02028174],
       [0.06052869, 0.06489432, 0.

In [38]:
#寻找最优和最劣解
A_best=np.zeros(J)
A_worst=np.zeros(J)
for j in range(J):
    A_best[j]=max(V[:,j])
    A_worst[j]=min(V[:,j])
A_best,A_worst

(array([0.07219875, 0.07286894, 0.0688861 , 0.00866389, 0.02028174]),
 array([0.05959509, 0.0561881 , 0.06226642, 0.00321752, 0.0127019 ]))

In [39]:
#计算距离
def get_dist(A,B):
    return np.sqrt((A-B)@(A-B))

ans=np.zeros(I)
for i in range(I):
    S_best=get_dist(V[i],A_best)
    S_worst=get_dist(V[i],A_worst)
    ans[i]=S_worst/(S_best+S_worst)
ans

array([0.85780751, 0.83533823, 0.81829637, 0.79372493, 0.75428354,
       0.76386023, 0.73826343, 0.68917051, 0.62377346, 0.54350468,
       0.57470561, 0.53780747, 0.50917744, 0.53947085, 0.44119406,
       0.41194892, 0.44656898, 0.40099031, 0.34925963, 0.29562445])

In [40]:
ans_index = sorted(range(len(ans)), key=lambda k: ans[k], reverse=True)
ans_index=[i+1 for i in ans_index]
ans_index

[1, 2, 3, 4, 6, 5, 7, 8, 9, 11, 10, 14, 12, 13, 17, 15, 16, 18, 19, 20]