In [2]:
#LU分解求Ax=b
#过程：A=LU,LZ=b,Ux=Z
 
import numpy as np
import pandas as pd
from scipy import linalg
 
np.random.seed(2)
def LU_decomposition(A,b):
    n=len(A[0])
    L = np.zeros([n,n])
    U = np.zeros([n, n])
    for i in range(n):
        L[i][i]=1
        if i==0:
            U[0][0] = A[0][0]
            for j in range(1,n):
                U[0][j]=A[0][j]
                L[j][0]=A[j][0]/U[0][0]
        else:
                for j in range(i, n):#U
                    temp=0
                    for k in range(0, i):
                        temp = temp+L[i][k] * U[k][j]
                    U[i][j]=A[i][j]-temp
                for j in range(i+1, n):#L
                    temp = 0
                    for k in range(0, i ):
                        temp = temp + L[j][k] * U[k][i]
                    L[j][i] = (A[j][i] - temp)/U[i][i]
    
    Z=linalg.solve(L, b)
    x=linalg.solve(U, Z)
    
    print("L=",L)
    print("U=",U)
    print("Z=",Z)
    print("Exact solution: x=",x)
    
    return
 
#定义A,b的值
A = np.array([
    [3, 2, -1, 4],
    [2, 3, 2, -1],
    [1, -1, 4, 2],
    [4, 1, -3, 3]
])
b = np.array([10, 7, 12, 6])
 
LU_decomposition(A,b)

L= [[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [ 0.33333333 -1.          1.          0.        ]
 [ 1.33333333 -1.          0.14285714  1.        ]]
U= [[ 3.          2.         -1.          4.        ]
 [ 0.          1.66666667  2.66666667 -3.66666667]
 [ 0.          0.          7.         -3.        ]
 [ 0.          0.          0.         -5.57142857]]
Z= [10.          0.33333333  9.         -8.28571429]
Exact solution: x= [1.72820513 0.39487179 1.92307692 1.48717949]


In [3]:
import numpy as np

# 初始化B向量
B = np.array([10, 7, 12, 6], dtype=float)

# 初始向量
x = np.ones_like(B)

# 设置迭代次数
iterations = 10

# 高斯-赛德尔迭代法
for _ in range(iterations):
    x_new = np.copy(x)
    x_new[0] = (1/3) * (B[0] - 2 * x[1] + x[2] - 4 * x[3])
    x_new[1] = (1/3) * (B[1] - 2 * x_new[0] - 2 * x[2] + x[3])
    x_new[2] = (1/4) * (B[2] - x_new[0] + x_new[1] - 2 * x[3])
    x_new[3] = (1/3) * (B[3] - 4 * x_new[0] - x_new[1] + 3 * x_new[2])
    x = x_new
    print(f"Iteration {_+1}: {x}")

# 打印最终结果
solution = x
solution


Iteration 1: [1.66666667 0.88888889 2.30555556 1.78703704]
Iteration 2: [1.12654321 0.6409465  1.9850823  2.26937586]
Iteration 3: [0.54189529 1.40514022 2.0811233  2.89021618]
Iteration 4: [-0.76334062  2.41821693  2.3502813   4.56199648]
Iteration 5: [-3.57804616  4.67250873  2.78164048  7.99486578]
Iteration 6: [-9.51428003  9.48671496  3.75281586 15.27628425]
Iteration 7: [-22.10858369  19.66260664   5.80465546  30.72856483]
Iteration 8: [-48.81160571  41.24748844  10.15049112  63.48346925]
Iteration 9: [-105.42612093   87.01157629   19.36768968  132.93199215]
Iteration 10: [-225.46114383  184.03963349   38.90919825  280.1775122 ]


array([-225.46114383,  184.03963349,   38.90919825,  280.1775122 ])

In [4]:
import numpy as np

# 构造矩阵B
B = np.array([[0, -2/3, 1/3, -4/3],
              [-2/3, 0, -2/3, 1/3],
              [-1/4, 1/4, 0, -1/2],
              [-4/3, -1/3, 3/4, 0]])

# 计算特征值
eigenvalues = np.linalg.eigvals(B)

# 计算谱半径
spectral_radius = max(abs(eigenvalues))

# 打印结果
print("Eigenvalues of B:", eigenvalues)
print("Spectral radius of B:", spectral_radius)

# 判断收敛性
if spectral_radius < 1:
    print("The Gauss-Seidel method converges.")
else:
    print("The Gauss-Seidel method does not converge.")


Eigenvalues of B: [ 1.45455098+0.j        -1.34973528+0.j        -0.05240785+0.6966975j
 -0.05240785-0.6966975j]
Spectral radius of B: 1.4545509773794105
The Gauss-Seidel method does not converge.
