In [9]:
import numpy as np
from scipy.spatial.transform import Rotation
import copy

theta=np.radians(30)
v=10
vel=np.array([v*np.cos(theta),0,v*np.sin(theta)])

N=1000
t_max=10
dt=t_max/N
G=6.67e-11
m=190
M=5.965e24
R=6371.393e3
# h=400e3
h=0
pos=np.array([0.,0.,h])
pos_list=[]

for i in range(N):
    tmp=np.cross(vel,(np.cross(vel,np.array([0,0,1]))))
    axis=tmp*dt/np.linalg.norm(tmp)
    rotation = Rotation.from_rotvec(axis)
    vel=rotation.apply(vel)
    print(pos)
    d=1.5*np.e**(-h/6450)
    a=G*M*(1-d*v**2/(47**2))/(h+R)**2
    vel[2]-=a*dt
    pos+=vel*dt
    pos_list.append(copy.deepcopy(pos))
    
import plotly.graph_objects as go
data=np.array(pos_list)
fig = go.Figure(data=[go.Scatter3d(
    x=data[:,0],  # 设置3个不同的坐标数据
    y=data[:,1], 
    z=data[:,2],
    mode='lines')])  # 'lines', 'markers', 'text'  3种情况的组合
fig.show()

[0. 0. 0.]
[ 0.08659821 -0.00099998  0.04908396]
[ 0.1731806  -0.0029953   0.09725192]
[ 0.25973582 -0.00598122  0.14450394]
[ 0.34625271 -0.00995298  0.19084005]
[ 0.43272022 -0.01490573  0.2362603 ]
[ 0.51912749 -0.02083459  0.28076474]
[ 0.60546378 -0.0277346   0.32435341]
[ 0.69171851 -0.03560078  0.36702637]
[ 0.77788124 -0.04442811  0.40878364]
[ 0.86394166 -0.05421151  0.44962529]
[ 0.94988962 -0.06494589  0.48955136]
[ 1.03571508 -0.07662612  0.52856189]
[ 1.12140816 -0.08924703  0.56665692]
[ 1.20695907 -0.10280343  0.60383652]
[ 1.29235819 -0.11729014  0.64010071]
[ 1.37759598 -0.13270192  0.67544954]
[ 1.46266306 -0.14903354  0.70988307]
[ 1.54755015 -0.16627974  0.74340134]
[ 1.63224806 -0.18443527  0.77600438]
[ 1.71674776 -0.20349487  0.80769226]
[ 1.80104029 -0.22345326  0.83846501]
[ 1.8851168  -0.24430517  0.86832268]
[ 1.96896855 -0.26604534  0.89726532]
[ 2.0525869  -0.28866848  0.92529297]
[ 2.1359633  -0.31216934  0.95240568]
[ 2.21908928 -0.33654266  0.97860349]
[

In [10]:
data

array([[ 8.65982103e-02, -9.99983333e-04,  4.90839589e-02],
       [ 1.73180597e-01, -2.99529768e-03,  9.72519224e-02],
       [ 2.59735823e-01, -5.98122431e-03,  1.44503936e-01],
       ...,
       [-4.33017568e-01, -1.06037702e+01, -3.99253071e+02],
       [-5.03387829e-01, -1.04452350e+01, -4.00095738e+02],
       [-5.65891221e-01, -1.02832174e+01, -4.00939277e+02]])